### ISSUE TITLE
Cannot sum with string condition => "Error: Unknown column 'SUM(reaction.action = 'like')' in 'field list'"

### ISSUE THREAD

**Issue by khanifikhsanudin** [nodeonline/mysql-query-builder#13]
code:
const query = select().from("reaction");
query.select("SUM(reaction.action = 'like')", "amount_like");
var sql = query.sql();

sql variable will return "SELECT \`SUM(reaction.action = 'like')\` AS amount_like FROM reaction" and if i execute the sql will be error.
I need return **SELECT SUM(reaction.action = 'like') AS amount_like FROM reaction** without this -> ``

**Comment by nodeonline** [comment]
Hi @khanifikhsanudin ,

Thanks for submiting the issue. I will take a look

**Comment by nodeonline** [comment]
Hi @khanifikhsanudin ,

You can change "'" to "`", then it should work
SELECT SUM(reaction.action = 'like') ===> SELECT SUM(reaction.action = `like`)

Thanks
